name: venv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    # jupyter
    - ipykernel
    # test suite: pytest
    - pytest
    - pytest-asyncio
    - pytest-cov
    # tool for updating semantic versioning over multiple files
    - bumpver
    # tools for building package for PyPI
    - build
    - twine
