site_name: "TheCodeCrate's Pipeline"
site_url: "https://thecodecrate.github.io/python-pipeline"
repo_url: "https://github.com/thecodecrate/python-pipeline"

watch:
  - src

extra_css:
  - assets/css/extra.css
  - assets/css/extra-pymdownx.css

theme:
  name: material
  # logo: assets/images/logo.svg
  # favicon: assets/images/favicon.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/theme-light-dark
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: deep purple
    accent: deep purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: dracula
    primary: deep purple
    accent: deep purple
    toggle:
      icon: material/weather-night
      name: Switch to system preference

  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - toc.integrate
    - toc.follow
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking

markdown_extensions:
  - markdown.extensions.attr_list:
  - markdown.extensions.md_in_html:
  - markdown.extensions.toc:
      anchorlink: true
      anchorlink_class: "toclink"
  - pymdownx.blocks.admonition:
      types:
      - new
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote
  - pymdownx.blocks.tab:
      alternate_style: True
      combine_header_slug: True
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - pymdownx.blocks.caption:
  - pymdownx.details:
  - pymdownx.snippets:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      normalize_issue_symbols: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - pymdownx.keys:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      extend_pygments_lang:
        - name: pycon3
          lang: pycon
          options:
            python3: true

plugins:
  # - autorefs
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["src"]
          options:
            show_if_no_docstring: true
            docstring_options:
              ignore_init_summary: true
              trim_doctest_flags: true
            docstring_section_style: list
            # docstring_section_style: spacy
            filters:
              - "!^_"
            heading_level: 1
            merge_init_into_class: true
            parameter_headings: true
            allow_inspection: true
            preload_modules: ["_api", "thecodecrate_pipeline",]
            relative_crossrefs: true
            scoped_crossrefs: true
            separate_signature: true
            # line_length: 60
            show_bases: false
            # show_inheritance_diagram: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: false
            unwrap_annotated: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thecodecrate/python-pipeline
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/thecodecrate-pipeline/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

nav:
  - Home: index.md
  - API Reference:
    - core: api/core.md
    - types: api/types.md
    - processors: api/processors.md
