name = "core"
plugins = [
    "_01_with_base",
    "_02_with_pipeline_as_list",
    "_03_with_stage_as_callable",
    "_04_with_pipeline_declared_stages",
    "_05_with_pipeline_factory",
    "_06_with_pipeline_processor",
    "_08_with_pipeline_as_stage",
    "_99_with_pipeline_default_processor",
]
