name: Check & fix styling with Ruff

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  format-ruff:
    name: Ruff Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run ruff format
        run: ruff format --output-format=github .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
