name: Check & fix styling with Ruff

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  format-ruff:
    name: Ruff Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Run ruff
        run: uvx ruff format .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
