name: Lint with Ruff

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-ruff:
    name: Ruff Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        run: ruff check --output-format=github .
