name: "Deploy package to PyPI"

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        run: uv python install

      - name: Build
        run: uv build

      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish
